### ISSUE TITLE
ModuleNotFoundError: No module named 'asr_metrics'

### ISSUE THREAD

**Issue by donghahaha** [hyeonsangjeon/computing-Korean-STT-error-rates#1]
우선 좋은 한국어 stt metric 만들어주셔서 감사합니다.<br/>
한가지 이슈가 있어서 문의 드립니다 ㅎㅎ

![image](https://user-images.githubusercontent.com/90599433/174508737-30702248-a9bf-43db-97a9-2f754efee947.png)
위에 사진처럼 asr_metrics 가상환경에 잘 설치되어 있는 데,
python 파일을 실행시키면 ModuleNotFoundError: No module named 'asr_metrics' 에러가 뜹니다.
혹시 경험에 비추어서 해결방법을 알고 계시나요?

**Comment by hyeonsangjeon** [comment]
안녕하세요. 아직 파이썬 패키지 라이브러리로 올리지 않았습니다. 패키지로는 좀더 기능들을 모아서 올릴예정입니다. 
excution python 파일과 asr_metrics.py가 동일 경로에두고,
from asr_metrics import functionX 로 import하시면 실행되실거에요.

**Comment by hyeonsangjeon** [comment]
pypi.org에 패키지로 올렸습니다. 
`pip install nlptutti`
